force-app/main/default/objects/Assignment_History__c/Assignment_History__c.object-meta.xml
<CustomObject>
    <label>Assignment History</label>
    <nameField>
        <displayFormat>TAH-{000000}</displayFormat>
        <label>Assignment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_History__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/New_Territory__c.field-meta.xml
<CustomField>
    <fullName>New_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Assignment Histories (New Territory)</relationshipLabel>
    <relationshipName>Assignment_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>

    <label>Zip Code</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
    public static void beforeInsert(List<Account> newAccounts){
        List<Account> assignTerritory = new List<Account>();
            
        for(Account acc : newAccounts){
            if(acc.BillingPostalCode != null){
                assignTerritory.add(acc);
            }
        }
        
        if(assignTerritory != null && assignTerritory.size() > 0){
            AccountController.checkOwnerMatchesTerritory(assignTerritory);
        }
    }
    
    public static void afterInsert(List<Account> updatedAccounts, Map<Id,Account> oldAccounts){
        List<Assignment_History__c> insertHistories = new List<Assignment_History__c>();

        for(Account acc : updatedAccounts){
            Assignment_History__c history = new Assignment_History__c();
            history.Account__c = acc.Id;
            history.New_Territory__c = acc.Territory__c;
            history.New_Owner__c = acc.OwnerId;
        }

        insert insertHistories;
    }
    
    public static void beforeUpdate(List<Account> updatedAccounts, Map<Id,Account> oldMap){
        List<Account> assignTerritory = new List<Account>();
        
        for(Account acc : updatedAccounts){
            if(acc.BillingPostalCode != oldMap.get(acc.Id).BillingPostalCode){
                assignTerritory.add(acc);
            }
        }
        
        List<Account> accountsWithNewOwner = new List<Account>();
        if(assignTerritory != null && assignTerritory.size() > 0){
            System.debug('assignTerritory is not null : ' + assignTerritory);
            accountsWithNewOwner = AccountController.checkOwnerMatchesTerritory(assignTerritory);
            System.debug('accountsWithNewOwner = ' + accountsWithNewOwner);
            
            // Finally update Account, Contact, and Opp owners!
            AccountController.reassignAccountContactAndOpp(accountsWithNewOwner , TRUE);

            // Create Territory Assignment records
            AccountController.createAssignmentHistory(accountsWithNewOwner, oldMap);
        }
    }
}