force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>

    <label>Zip Code</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Number_of_TAs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_TAs__c</fullName>
    <label>Number of TAs</label>
    <summaryForeignKey>Territory_Assignment__c.Territory__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TerritoryTriggerHandler.cls
public with sharing class TerritoryTriggerHandler {
    public static void beforeUpdate(List<Territory__c> newTerritories, Map<Id,Territory__c> oldTerritories){
        // Reassign accounts in this territory if the Name (Zip Code) changed or if the number of TA's changed
        List<Territory__c> territoriesNeedingReassignment = new List<Territory__c>();
        for(Territory__c t : newTerritories){
            if(t.Name != oldTerritories.get(t.Id).Name || t.Number_Of_TAs__c != oldTerritories.get(t.Id).Number_Of_TAs__c){
                territoriesNeedingReassignment.add(t);
            }
        }
        
        if(territoriesNeedingReassignment != null && territoriesNeedingReassignment.size() > 0){
            TerritoryController tc = new TerritoryController();
            List<Account> ressignedAccounts = tc.processTriggeredTerritories(territoriesNeedingReassignment);
            AccountController.reassignAccountContactAndOpp(ressignedAccounts, FALSE);
        }
    }
}