force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>

    <label>Zip Code</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{00000}</displayFormat>
        <label>Territory Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Assignment__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/Duplicate_Key__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Key__c</fullName>
    <description>Trigger concatenates the Zip Code &amp; Assignee value to produce a unique value.  Field flagged as unique to prevent duplicates</description>
    <externalId>true</externalId>
    <label>Duplicate Key</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryAssignmentTriggerHandler.cls
public with sharing class TerritoryAssignmentTriggerHandler {
    public static void beforeInsert(List<Territory_Assignment__c> newTAs){
        for(Territory_Assignment__c t : newTAs){
            t.Duplicate_Key__c = t.Territory__c + '' + t.Assignee__c;
        }
    }

    public static void beforeUpdate(List<Territory_Assignment__c> newTAs, Map<Id,Territory_Assignment__c> oldTAsMap){
        for(Territory_Assignment__c t : newTAs){
            if(t.Territory__c + '' + t.Assignee__c != oldTAsMap.get(t.Id).Duplicate_Key__c){
                t.Duplicate_Key__c = t.Territory__c + '' + t.Assignee__c;
            }
        }
    }
    
    public static void afterUpdate(List<Territory_Assignment__c> newTAs, Map<Id,Territory_Assignment__c> oldTAs){
        Set<Id> reassignTerritoryIDs = new Set<Id>();

        for(Territory_Assignment__c newTA : newTAs){
            if(newTA.Assignee__c != oldTAs.get(newTA.Id).Assignee__c){
                reassignTerritoryIDs.add(newTA.Territory__c);
            }
        }

        if(reassignTerritoryIDs != null && reassignTerritoryIDs.size() > 0){
            List<Territory__c> reassignTerritories = [SELECT Id, Name FROM Territory__c WHERE Id IN :reassignTerritoryIDs];
            TerritoryController tc = new TerritoryController();
            List<Account> reassignedAccounts = tc.processTriggeredTerritories(reassignTerritories);
            if(reassignedAccounts != null && reassignedAccounts.size() > 0){
                AccountController.reassignAccountContactAndOpp(reassignedAccounts, FALSE);
            }
        }
    }
}